server:
  port: 8090
management:
  port: 8091

endpoints:
  enabled: false
  health:
    enabled: true

spring:
  activemq:
    username: admin
    password: admin
    broker-url: tcp://localhost:61616

logging:
  level:
    root: debug
    sun.rmi: info
